

# Introduction {#intro}
New Graph Environment and Nupqu Limited Partnership were retained by the Canadian Wildlife Federation in the fall of 2020 to plan and conduct fish passage and habitat confirmation assessments at road-stream crossings as part of connectivity restoration planning targeting westslope cutthrout trout. Although some planning was conducted for both the Elk River watershed upstream of the Elko Dam near Elko, BC and the Flathead River, on the ground surveys in 2020 focused on the Elk River and tributaries located upstream of the Elko Dam. `r if(identical(html_on, FALSE))knitr::asis_output("This report is available as pdf and as an html document online [interactive report](https://newgraphenvironment.github.io/fish_passage_elk_2020_reporting_cwf/) at https://newgraphenvironment.github.io/fish_passage_elk_2020_reporting_cwf/. We recommend viewing online as the web-hosted html version contains more features and is more easily navigable.")` 

<br>

The health and viability of freshwater fish populations can depend on access to tributary and off channel areas which provide refuge during high flows, opportunities for foraging, overwintering habitat, spawning habitat and summer rearing habitat [@Bramblett_2002; @swalesRoleOffChannelPonds1989; @diebel_etal2015EffectsRoad].  Culverts can present barriers to upstream and downstream fish migration due to low water depth, increased water velocity, turbulence, a vertical drop at the culvert outlet and/or maintenance issues [@slaneyFishHabitatRehabilitation1997; @cote_etal2005Fishpassage]. Reconnecting fragmented habitats by culvert removal or replacement is a management action that can generate high ecological returns relative to other habitat restoration techniques [@saldicaromileStreamHabitatRestoration2004; @roni_etal2008GlobalReview]. As road and rail systems are commonly upgraded there are numerous opportunities to restore connectivity by ensuring that fish passage considerations are incorporated into repair, replacement and relocation/decommisioning designs.
